typography_spectrum: 0.15010622469708323
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9843458677642047
  lightness: 0.9685762310400605
  saturation: 0.8973167166113853
  rhythmicContrast: 0.7855365118011832
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6961738602258265
analytics:
  google: null
  facebook: null
  twitter: null
name: emcarta
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Heart
description: Public care and education on demand
purpose: []
